<!doctype html><html xmlns=http://www.w3.org/1999/xhtml xml:lang=en-us lang=en-us><head><link href=https://gmpg.org/xfn/11 rel=profile><meta charset=utf-8><meta name=generator content="Hugo 0.134.2"><meta name=viewport content="width=device-width,initial-scale=1"><title>Azure Function Encountered an Error ServiceUnavailable From Host Runtime &#183; by Alex Code blog</title>
<meta name=description content="Syncing triggers (Attempt 6/6)... Error: Encountered an error (ServiceUnavailable) from host runtime."><link type=text/css rel=stylesheet href=https://byalexblog.net/css/print.css media=print><link type=text/css rel=stylesheet href=https://byalexblog.net/css/poole.css><link type=text/css rel=stylesheet href=https://byalexblog.net/css/syntax.css><link type=text/css rel=stylesheet href=https://byalexblog.net/css/hyde.css><link type=text/css rel=stylesheet href=https://byalexblog.net/css/vs_theme_style.css><link rel=stylesheet href="https://fonts.googleapis.com/css?family=Abril+Fatface|PT+Sans:400,400i,700"><link rel=apple-touch-icon-precomposed sizes=144x144 href=/apple-touch-icon-144-precomposed.png><link rel="shortcut icon" href=/favicon.png></head><body><aside class=sidebar><div class=container><div class=sidebar-about><a href=https://byalexblog.net/><h1>by Alex Code blog</h1></a><p class=lead>Smart thoughts... and not very smart too!</p></div><nav><ul class=sidebar-nav><li><a href=https://byalexblog.net/>Home</a></li><li><a href=https://byalexblog.net/article>Articles</a></li><li><a href=https://github.com/lanubisl target=_blank>Github</a></li><li><a href=https://www.linkedin.com/in/panfilenok target=_blank>LinkedIn</a></li></ul></nav><p>&copy; 2024. All rights reserved.</p></div></aside><main class="content container"><div class=post><h1>Azure Function Encountered an Error ServiceUnavailable From Host Runtime</h1><time datetime=2024-02-10T10:03:16Z class=post-date>Sat, Feb 10, 2024</time><p><img src=/images/azure-function-encountered-an-error-serviceunavailable-from-host-runtime/logo.webp alt></p><p>I recently had an issue deploying Python 3.10 Azure Function on App Service Plan. The error message was:</p><pre tabindex=0><code>9:38:43 AM myfunc: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
9:38:56 AM myfunc: Syncing triggers...
9:39:50 AM myfunc: Syncing triggers (Attempt 2/6)...
9:40:51 AM myfunc: Syncing triggers (Attempt 3/6)...
9:42:01 AM myfunc: Syncing triggers (Attempt 4/6)...
9:43:01 AM myfunc: Syncing triggers (Attempt 5/6)...
9:45:12 AM myfunc: Syncing triggers (Attempt 6/6)...
9:45:33 AM: Error: Encountered an error (ServiceUnavailable) from host runtime.
</code></pre><h2 id=introduction>Introduction</h2><p>On one of by Azure Function App, I had to change the synchronious trigger to asynchronious trigger. This is the <a href=https://learn.microsoft.com/en-us/azure/azure-functions/python-scale-performance-reference target=_blank rel=noopener>best practice</a> for case when your function has some io-bound operations.</p><p>Here is what I did:</p><ol><li>I added <code>async</code> keyword to the function definition.</li><li>Add peckages <code>aiohttp</code> and <code>asyncio</code> to the <code>requirements.txt</code> file.</li><li>Changed all the requests to asynchronious requests using <code>aiohttp</code> package.</li></ol><p>Here is just an example of the function that can replicate the issue:</p><h4 id=function_apppy>function_app.py</h4><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> azure.functions <span style=color:#66d9ef>as</span> func
</span></span><span style=display:flex><span><span style=color:#f92672>import</span> asyncio
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>app <span style=color:#f92672>=</span> func<span style=color:#f92672>.</span>FunctionApp(http_auth_level<span style=color:#f92672>=</span>func<span style=color:#f92672>.</span>AuthLevel<span style=color:#f92672>.</span>ANONYMOUS)
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#a6e22e>@app.function_name</span>(name<span style=color:#f92672>=</span><span style=color:#e6db74>&#34;health&#34;</span>)
</span></span><span style=display:flex><span><span style=color:#a6e22e>@app.route</span>(route<span style=color:#f92672>=</span><span style=color:#e6db74>&#34;health&#34;</span>)
</span></span><span style=display:flex><span><span style=color:#66d9ef>async</span> <span style=color:#66d9ef>def</span> <span style=color:#a6e22e>health_function</span>(req: func<span style=color:#f92672>.</span>HttpRequest) <span style=color:#f92672>-&gt;</span> func<span style=color:#f92672>.</span>HttpResponse:
</span></span><span style=display:flex><span>    
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>await</span> asyncio<span style=color:#f92672>.</span>sleep(<span style=color:#ae81ff>1</span>)
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>return</span> func<span style=color:#f92672>.</span>HttpResponse(<span style=color:#e6db74>&#34;OK&#34;</span>)
</span></span></code></pre></div><h4 id=requirementstxt>requirements.txt</h4><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-txt data-lang=txt><span style=display:flex><span># DO NOT include azure-functions-worker in this file
</span></span><span style=display:flex><span># The Python Worker is managed by Azure Functions platform
</span></span><span style=display:flex><span># Manually managing azure-functions-worker may cause unexpected issues
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>azure-functions
</span></span><span style=display:flex><span>aiohttp
</span></span><span style=display:flex><span>asyncio
</span></span></code></pre></div><p>After I tried to deploy the function, I got the error message. I tried to deploy the function multiple times but the error was still there.
After 6 attempts to synchronize triggers, the deployment failed with the error message <code>Error: Encountered an error (ServiceUnavailable) from host runtime.</code></p><h2 id=googling>Googling</h2><p>Similar problem was described <a href=https://hungchienhsiang.medium.com/error-encountered-an-error-serviceunavailable-from-host-runtime-9088cb63835c target=_blank rel=noopener>here</a> (no working solution), <a href=https://learn.microsoft.com/en-us/answers/questions/1398281/azure-function-app-error-encountered-an-error-%28ser%29 target=_blank rel=noopener>here</a> (solution did not work for me), <a href=https://github.com/microsoft/azure-pipelines-tasks/issues/16942 target=_blank rel=noopener>here</a> (github issue, no solution) and <a href=https://learn.microsoft.com/en-us/answers/questions/1275484/function-app-deployment-error target=_blank rel=noopener>here</a> (no solution).</p><h2 id=investigation>Investigation</h2><p>I have tried many different things to get the internals of the error. Here is the thing that finally gave me the clue.</p><ol><li>Go to <a href=https://learn.microsoft.com/en-us/azure/app-service/resources-kudu target=_blank rel=noopener>Kudu service UI</a> for your app. Please note: This will not work for <em>Consumption Plan</em> but since we are using <em>App Service Plan</em> it will work. Just take your function url and replace <code>https://&lt;function_name>.azurewebsites.net</code> with <code>https://&lt;function_name>.scm.azurewebsites.net</code>.</li><li>Switch to the <em>New Kudu UI</em> by adding the &rsquo;newui&rsquo; to the URL. So the URL will look like <code>https://&lt;function_name>.scm.azurewebsites.net/newui</code>.
It will look like this:
<img src=/images/azure-function-encountered-an-error-serviceunavailable-from-host-runtime/kudu_new_ui.png alt></li><li>Go to the File Manager -> /LogFiles/Application/Functions/Host/ and open log file started with date. Scroll down and you will see the following:</li></ol><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-text data-lang=text><span style=display:flex><span>[Information] Starting JobHost
</span></span><span style=display:flex><span>[Information] Starting Host (HostId=dedicated-python-test, InstanceId=2462a8c5-981d-45ea-b9b3-f8bd31fb18e1, Version=4.28.4.4, ProcessId=27, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
</span></span><span style=display:flex><span>[Information] Loading functions metadata
</span></span><span style=display:flex><span>[Information] Traceback (most recent call last):
</span></span><span style=display:flex><span>[Information] File &#34;/usr/local/lib/python3.10/runpy.py&#34;, line 196, in _run_module_as_main
</span></span><span style=display:flex><span>[Information] return _run_code(code, main_globals, None,
</span></span><span style=display:flex><span>[Information] File &#34;/usr/local/lib/python3.10/runpy.py&#34;, line 86, in _run_code
</span></span><span style=display:flex><span>[Information] exec(code, run_globals)
</span></span><span style=display:flex><span>[Information] File &#34;/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/__main__.py&#34;, line 6, in &lt;module&gt;
</span></span><span style=display:flex><span>[Information] main.main()
</span></span><span style=display:flex><span>[Information] File &#34;/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/main.py&#34;, line 49, in main
</span></span><span style=display:flex><span>[Information] from ._thirdparty import aio_compat
</span></span><span style=display:flex><span>[Information] File &#34;/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/_thirdparty/aio_compat.py&#34;, line 8, in &lt;module&gt;
</span></span><span style=display:flex><span>[Information] import asyncio
</span></span><span style=display:flex><span>[Information] File &#34;/home/site/wwwroot/.python_packages/lib/site-packages/asyncio/__init__.py&#34;, line 21, in &lt;module&gt;
</span></span><span style=display:flex><span>[Information] from .base_events import *
</span></span><span style=display:flex><span>[Information] File &#34;/home/site/wwwroot/.python_packages/lib/site-packages/asyncio/base_events.py&#34;, line 296
</span></span><span style=display:flex><span>[Information] future = tasks.async(future, loop=self)
</span></span><span style=display:flex><span>[Information] ^^^^^
</span></span><span style=display:flex><span>[Error] SyntaxError: invalid syntax
</span></span><span style=display:flex><span>[Error] Exceeded language worker restart retry count for runtime:python. Shutting down and proactively recycling the Functions Host to recover
</span></span></code></pre></div><ol start=4><li>Finaly some useful information. The error is <code>SyntaxError: invalid syntax</code> and the file that caused the error is <code>base_events.py</code>. The error is caused by the line <code>future = tasks.async(future, loop=self)</code>. This is the line from the <code>asyncio</code> package. The error is caused by the fact that <code>async</code> is a keyword in Python 3.10 and it cannot be used as a function name.</li><li>Here is what helped me to fix the issue: <a href=https://github.com/pyinstaller/pyinstaller/issues/6156 target=_blank rel=noopener>https://github.com/pyinstaller/pyinstaller/issues/6156</a></li></ol><h2 id=solution>Solution</h2><p>Just remove the <code>asyncio</code> package from the <code>requirements.txt</code> file. The <code>asyncio</code> package is included in the Python runtime and you do not need to include it in the <code>requirements.txt</code> file.</p></div><h2>Comments</h2><div id=disqus_thread></div><script>window.disqus_config=function(){},function(){if(["localhost","127.0.0.1"].indexOf(window.location.hostname)!=-1){document.getElementById("disqus_thread").innerHTML="Disqus comments not available by default when the website is previewed locally.";return}var t=document,e=t.createElement("script");e.async=!0,e.src="//byalexblog.disqus.com/embed.js",e.setAttribute("data-timestamp",+new Date),(t.head||t.body).appendChild(e)}()</script><noscript>Please enable JavaScript to view the <a href=https://disqus.com/?ref_noscript>comments powered by Disqus.</a></noscript><a href=https://disqus.com class=dsq-brlink>comments powered by <span class=logo-disqus>Disqus</span></a></main></body></html>